---
version: 2
multicolumn: false
web-width: '200'
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/rplot_bar_1/rplot_bar_1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/224017/articles/342767/master/file/figures/rplot_bar_1/rplot_bar_1.png"
    folder_url: "/users/224017/articles/342767/master/folder/figures/rplot_bar_1"
