---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/rplot_abline_2/rplot_abline_2.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/224017/articles/342767/master/folder/figures/rplot_abline_2"
    url: "/users/224017/articles/342767/master/file/figures/rplot_abline_2/rplot_abline_2.png"
